spring:

  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: blog_app
    password: blog_app

  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

project:
  image: images/
